version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Build started on `date`
      - mvn install:install-file -Dfile=./src/main/resources/ojdbc7-11.2.0.jar -DgroupId=com.oracle -DartifactId=ojdbc7
      - -Dversion=12.1.0.2 -Dpackaging=jar
      - mvn test
  build:
    commands:
      - echo Build completed on `date`
