version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Build started on `date`
      #      - mvn install:install-file -Dfile=ojdbc7-11.2.0.jar
      - mvn test
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - mv target/p2-1.war
artifacts:
  files:
    - p2-1.war
    - .ebextensions/**/*
