version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  post_build:
    commands:
      - mvn package
      - mv target/p2-1.war p2-1.war
artifacts:
  files:
    - p2-1.war
    - .ebextensions/**/*
